name = "P2Poffo"
uuid = "15746f16-e5ef-480f-93b5-237a577d2332"
version = "0.1.0"
authors = ["PedroPoffo <pedrohenriquepoffo@gmail.com>"]

[deps]
Gmsh = "705231aa-382f-11e9-3f0c-b7cb4346fdeb"
LFrame = "ff7349aa-6be6-4087-9dfe-a9fea3953284"
Lgmsh = "901517f6-ef86-4a80-bf35-2c5b8e720204"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Gmsh = "0.3.1"
LFrame = "1.1.0"
Revise = "3.12.2"
Statistics = "1.11.1"
